import type { Difficulty, EnemyKind, ResourceKind, StructureKind, Tier, Upgrades } from "./types";
import { ENEMY_REGISTRY } from "./enemy-registry";

const ENEMY_BASE_STATS = Object.fromEntries(
  Object.values(ENEMY_REGISTRY).map((entry) => [entry.id, entry.base]),
) as Record<EnemyKind, (typeof ENEMY_REGISTRY)[EnemyKind]["base"]>;

export const BALANCE = {
  logicalWidth: 1280,
  logicalHeight: 720,
  fixedStep: 1 / 60,
  dayDuration: 60,
  nightDuration: 30,
  nightSpawnCutoff: 15,
  mapSize: 3600,
  tutorialArena: {
    radius: 344,
    fadeStart: 0.78,
    boundaryInset: 2,
  },
  flagGenerationRadius: 400,
  flagProtectedRadius: 200,
  player: {
    radius: 25,
    speed: 190,
    maxHealth: 100,
    punchRange: 78,
    punchArc: 0.92,
    punchDamage: 18,
    punchRate: 0.42,
    buildReach: 205,
    healRate: 3,
  },
  flag: {
    radius: 45,
    health: 150,
  },
  bow: {
    damage: 12,
    // Cooldown seconds. A 30% lower attack rate means the old cooldown divided by 0.70.
    rate: 0.42 / 0.70,
    speed: 940,
    range: 700,
    radius: 5,
  },
  portal: {
    radius: 50,
    health: 90,
    edgeMin: 1180,
    edgeMax: 1570,
    margin: 150,
    noBuildRadius: 290,
    relocationMinimumDistance: 580,
  },
  sunlight: {
    movementMultiplier: 0.5,
    startingDamage: 3,
    damageEscalation: 1.4,
    maximumDamage: 24,
    effectInterval: 0.16,
  },
  snowyEnemies: {
    slow: {
      movementMultiplier: 0.65,
      attackSpeedMultiplier: 0.65,
      tint: "#e7fbff",
      popupTextColor: "#63c6e8",
    },
  },
  tierMechanics: {
    desert: { sandstormRadius: 235, sandstormSpeedMultiplier: 2, tunnelDuration: 9, tunnelInterval: 1, tunnelExitDistance: 150 },
    volcanic: {
      burnDuration: 3.5,
      burnDamagePerSecond: 7,
      calderaBurnDuration: 2,
      cinderburstDamageMultiplier: 0.9,
    },
    wasteland: {
      radiationRadius: 230,
      radiationDamagePerSecond: 0.55,
      radiationActivationDuration: 1,
      radiationDayDecayDuration: 50,
      radiationFadeSizeRatio: 0.1,
      poisonDuration: 7,
      poisonDamagePerSecond: 3.5,
      standardAreaAttackCooldown: 4.25,
      largeAreaAttackFrequencyMultiplier: 0.5,
    },
    rift: {
      ghostDuration: 2,
      deathPortalDuration: 8,
      deathPortalSpawns: 5,
      deathPortalInterval: 1,
      bossGhostCount: 5,
      bossPortalDistance: 150,
      bossPortalDuration: 12,
      bossPortalSpawns: 8,
    },
    mire: {
      infectedFraction: 0.12,
      hintRadius: 190,
      tentacleDamage: 18,
      tentacleCooldown: 2.5,
      bossTentacleHealthRatio: 0.28,
      bossTentacleDamageRatio: 0.45,
      bossTentacleSpeed: 205,
      bossTentacleRadius: 16,
    },
    clockwork: {
      timedLifeSeconds: 10,
      dayPenaltyPerEarlyKill: 2,
      timeLockSeconds: 1,
      timeLockBurstRadius: 190,
      rewindFreezeSeconds: 1,
      rewindDuration: 3.4,
      rewindMergeDuration: 0.8,
    },
  },
  navigation: {
    cellSize: 72,
    obstacleMargin: 10,
    zombieClearance: 39,
    stuckRepathTime: 0.7,
    repathIntervalMin: 0.65,
    repathIntervalJitter: 0.35,
    zombieSeparationRadiusMultiplier: 0.5,
    zombieSeparationForce: 0.12,
    runnerMaximumDetourRatio: 1.65,
    runnerMaximumExtraDistance: 620,
    runnerRouteCommitmentDuration: 1.6,
    runnerRepathInterval: 0.75,
    targetRepathCooldown: 0.18,
    targetHysteresis: 1.12,
    overlapResolveSpeed: 210,
    fullyStuckAttackDelay: 1.5,
    fullyStuckMaximumProgressPerSecond: 0.25,
    stuckBlockerSearchPadding: 12,
  },
  ui: {
    dawnChoiceClickDelay: 0.5,
    messageDuration: 2.8,
    criticalMessageDuration: 4.5,
    tutorialPreferenceKey: "countdown-forest-tutorial-seen",
    clockShakeStrength: 1.8,
    playerWarningCooldown: 20,
    flagWarningCooldown: 1.1,
    doorFadeRadius: 112,
    doorFadedOpacity: 0.38,
    statusPopupStrokeColor: "rgba(9,40,52,.92)",
    cardSelectionDuration: 420,
    cardTransitionDuration: 520,
    cardTransitionEasing: "ease-in-out",
    turretRangePreview: {
      currentStroke: "rgba(207, 246, 225, .72)",
      upgradedStroke: "rgba(116, 243, 165, .9)",
      fill: "rgba(116, 243, 165, .055)",
      lineWidth: 8,
      dash: [10, 8],
    },
    costLayout: {
      iconSize: 20,
      itemGap: 8,
      rowGap: 5,
    },
  },
  resource: {
    radius: { wood: 42, stone: 35, gold: 30, diamond: 27 } satisfies Record<ResourceKind, number>,
    health: { wood: 18, stone: 22, gold: 18, diamond: 12 } satisfies Record<ResourceKind, number>,
    counts: { wood: 105, stone: 58, gold: 18, diamond: 8 } satisfies Record<ResourceKind, number>,
    minimumBoundarySeparation: 78,
    generationRetries: 6,
    validationPortalDistance: 1420,
  },
  harvest: {
    wood: { wood: 2, stone: 1, gold: 0, diamond: 0 },
    stone: { wood: 4, stone: 2, gold: 1, diamond: 0 },
    gold: { wood: 8, stone: 4, gold: 2, diamond: 1 },
    diamond: { wood: 16, stone: 8, gold: 4, diamond: 2 },
  } satisfies Record<Tier, Record<ResourceKind, number>>,
  glovePortalDamage: { wood: 16, stone: 24, gold: 36, diamond: 52 } satisfies Record<Tier, number>,
  tierIndex: { wood: 0, stone: 1, gold: 2, diamond: 3 } satisfies Record<Tier, number>,
  tierColors: { wood: "#b77a45", stone: "#aeb7bc", gold: "#f6c945", diamond: "#57e5ef" } satisfies Record<Tier, string>,
  stageCosts: {
    wall: {
      wood: { wood: 10, stone: 0, gold: 0, diamond: 0 },
      stone: { wood: 0, stone: 7, gold: 0, diamond: 0 },
      gold: { wood: 0, stone: 0, gold: 5, diamond: 0 },
      diamond: { wood: 0, stone: 0, gold: 0, diamond: 3 },
    },
    door: {
      wood: { wood: 20, stone: 0, gold: 0, diamond: 0 },
      stone: { wood: 0, stone: 14, gold: 0, diamond: 0 },
      gold: { wood: 0, stone: 0, gold: 10, diamond: 0 },
      diamond: { wood: 0, stone: 0, gold: 0, diamond: 6 },
    },
    spikes: {
      wood: { wood: 14, stone: 0, gold: 0, diamond: 0 },
      stone: { wood: 0, stone: 9, gold: 0, diamond: 0 },
      gold: { wood: 0, stone: 0, gold: 7, diamond: 0 },
      diamond: { wood: 0, stone: 0, gold: 0, diamond: 4 },
    },
    harvester: {
      wood: { wood: 28, stone: 0, gold: 0, diamond: 0 },
      stone: { wood: 0, stone: 20, gold: 0, diamond: 0 },
      gold: { wood: 0, stone: 0, gold: 14, diamond: 0 },
      diamond: { wood: 0, stone: 0, gold: 0, diamond: 8 },
    },
    turret: {
      wood: { wood: 32, stone: 0, gold: 0, diamond: 0 },
      stone: { wood: 0, stone: 24, gold: 0, diamond: 0 },
      gold: { wood: 0, stone: 0, gold: 16, diamond: 0 },
      diamond: { wood: 0, stone: 0, gold: 0, diamond: 10 },
    },
  } satisfies Record<StructureKind, Record<Tier, Record<ResourceKind, number>>>,
  structure: {
    startingCapacity: { turret: 3, harvester: 3 },
    maximumCapacity: { turret: 8, harvester: 8 },
    radius: { wall: 34, door: 34, spikes: 34, harvester: 39, turret: 36 } satisfies Record<StructureKind, number>,
    health: {
      wall: [150, 260, 400, 580],
      door: [125, 215, 340, 500],
      spikes: [60, 105, 165, 248],
      harvester: [50, 90, 140, 200],
      turret: [110, 190, 300, 450],
    } satisfies Record<StructureKind, number[]>,
    spikeRetaliation: [4, 7, 11, 18],
    turretDamage: [8, 13, 20, 30],
    turretRange: [330, 370, 420, 480],
    turretRate: [1.25, 1.05, 0.82, 0.62],
    harvesterSpeed: [0.8, 1.02, 1.28, 1.6],
    harvesterArm: [98, 108, 120, 134],
  },
  repair: {
    interval: 0.22,
    healthPerHit: 8,
  },
  enemy: ENEMY_BASE_STATS,
  boss: {
    obstacleAttackRange: 18,
    obstaclePathWidth: 0.55,
    strongShakeMultiplier: 0.55,
  },
  punchHands: ["right", "left"] as const,
  harvester: {
    revolutionRadians: Math.PI * 2,
  },
  recycling: {
    rounding: "floor" as const,
  },
  nightMilestones: [
    { night: 1, enemy: "basic", label: "Basic zombie" },
    { night: 2, enemy: "runner", label: "Runner" },
    { night: 3, enemy: "breaker", label: "Tier 3 threat" },
    { night: 5, enemy: "jumper", label: "Tier 5 threat" },
    { night: 7, enemy: "summoner", label: "Tier 7 threat" },
    { night: 10, enemy: "boss", label: "Boss" },
  ] as const,
  introductionNight: Object.fromEntries(Object.values(ENEMY_REGISTRY).map((entry) => [entry.id, entry.introductionNight])) as Record<EnemyKind, number>,
  baseWeights: Object.fromEntries(Object.values(ENEMY_REGISTRY).map((entry) => [entry.id, entry.spawnWeight])) as Record<EnemyKind, number>,
  waveSafety: {
    maximumActiveEnemies: 90,
    maximumActiveChildren: 18,
    firstIntroductionShare: 0.28,
  },
  waveBase: 8,
  waveGrowth: 4,
  waveGrowthExponent: 1.08,
  endless: {
    firstNight: 11,
    rosterAdditionInterval: 5,
    waveGrowthPerNight: 1.085,
    maximumScheduledEnemies: 900,
    minimumSpecialThreatShare: 0.35,
    specialCapGrowthPerMilestone: 0.5,
    healthGrowthPerNight: 1.045,
    damageGrowthPerNight: 1.025,
    bossSpawnDelay: 12,
    bossHealthGrowthPerCycle: 1.55,
    bossDamageGrowthPerCycle: 1.16,
    fortPulse: {
      cost: { wood: 0, stone: 0, gold: 24, diamond: 8 },
      radius: 520,
      baseDamage: 90,
      maximumHealthDamage: 0.12,
    },
  },
  /**
   * Canonical fort value used by adaptive difficulty.
   *
   * Values are normalized to a Wood wall worth 10. Tier growth combines the
   * cumulative resource cost at 1/2/4/8 resource exchange weights with the
   * structure's existing health, retaliation, harvesting, or turret-DPS ratios.
   * This preserves the danger ordering while making material investment
   * and real combat/economic output visible in one configurable table.
   */
  structureValues: {
    wall: { wood: 10, stone: 20, gold: 34, diamond: 51 },
    door: { wood: 10, stone: 20, gold: 35, diamond: 52 },
    spikes: { wood: 13, stone: 26, gold: 45, diamond: 68 },
    harvester: { wood: 26, stone: 51, gold: 84, diamond: 123 },
    turret: { wood: 36, stone: 84, gold: 180, diamond: 380 },
  } satisfies Record<StructureKind, Record<Tier, number>>,
  adaptive: {
    expectedFortification: {
      startingPoints: 126,
      growthPerNight: 140,
      growthExponent: 1.2,
    },
    safeExpectedMinimum: 63,
    structure: {
      curve: "dead-zone-linear" as const,
      sensitivity: 0.72,
      deadZone: 0.05,
      minimumMultiplier: 0.5,
      maximumMultiplier: 1.85,
    },
    level: {
      curve: "linear" as const,
      baselineLevel: 1,
      deltaPerLevel: 0.015,
      minimumMultiplier: 1,
      maximumMultiplier: 1.6,
    },
    effective: {
      baseMultiplier: 1,
      minimumMultiplier: 0.5,
      // Power awareness adds effective DPS, range coverage, and capped player-upgrade progress.
      maximumMultiplier: 4,
    },
    healthInfluence: 0.16,
    damageInfluence: 0.1,
    specialWeightInfluence: 0.35,
    spawnFrequencyInfluence: 0.25,
    powerAwareness: {
      turretDps: {
        expectedStartingDps: 120,
        expectedGrowthPerNight: 20,
        expectedGrowthExponent: 1.05,
        deadZone: 0.1,
        sensitivity: 0.45,
        maximumDelta: 0.5,
      },
      turretCoverageThresholds: [
        { ratio: 0.45, delta: 0.05 },
        { ratio: 0.65, delta: 0.12 },
        { ratio: 0.85, delta: 0.22 },
        { ratio: 1.05, delta: 0.35 },
      ],
      turretCounterWeights: {
        coverageThreshold: 0.85,
        dpsRatioThreshold: 1.5,
        archerMultiplier: 2.5,
        acidslingerMultiplier: 2,
      },
      playerUpgrades: {
        maximumDelta: 0.45,
        weights: {
          moveSpeed: 1,
          maxHealth: 1,
          punchRate: 1,
          punchDamage: 1,
          bowRate: 1,
          bowDamage: 1,
          harvestRate: 0.5,
          repairEfficiency: 0.7,
          structureDurability: 0.8,
          costReduction: 0.5,
          turretDamage: 0,
          turretRate: 0,
          turretRange: 0,
          harvesterSpeed: 0.4,
          flagHealth: 0.8,
          turretCapacity: 0,
          harvesterCapacity: 0.4,
        } satisfies Record<keyof Upgrades, number>,
      },
      equipment: {
        referenceStrength: 1,
        maximumDeltaByKind: {
          helmet: 0.25,
          wrench: 0.25,
          sword: 0.4,
          mallet: 0.25,
        },
      },
    },
    pressureIndicator: {
      belowMaximum: 0.92,
      aboveMinimum: 1.08,
    },
    autoCorrective: {
      maximumDelta: 0.55,
      minimumDelta: -0.2,
      startingStrength: 0.35,
      fullStrengthAfterNight: 4,
      performanceWeights: {
        clearRate: 0.68,
        personalKillRate: 0.12,
        fullClear: 0.2,
      },
      pressureWeights: {
        totalIncomingDamage: 0.16,
        damagedStructureCount: 0.08,
        damagedStructureValue: 0.2,
        destroyedStructureCount: 0.18,
        destroyedStructureValue: 0.38,
        flagDamage: 0.9,
        zombiesEnteringFlagRadius: 0.18,
        playerDamageTaken: 0.72,
        survivingZombies: 0.42,
      },
      normalizers: {
        totalIncomingDamage: 220,
        damagedStructureCount: 4,
        damagedStructureValue: 240,
        destroyedStructureCount: 2,
        destroyedStructureValue: 160,
        zombiesEnteringFlagRadius: 8,
      },
    },
  },
  cracks: {
    thresholds: [0.001, 0.25, 0.5, 0.75],
  },
  reroll: {
    limit: 3,
    costFraction: 0.5,
  },
  debug: {
    navigation: false,
    adaptiveHud: false,
  },
  difficulty: {
    easy: { label: "Easy", enemyHealth: 0.78, enemyDamage: 0.72, enemySpeed: 0.92, attackSpeed: 0.9, spawnCount: 0.78, flagHealth: 1.35, xpMultiplier: 0.8 },
    normal: { label: "Normal", enemyHealth: 1, enemyDamage: 1, enemySpeed: 1, attackSpeed: 1, spawnCount: 1, flagHealth: 1, xpMultiplier: 1 },
    hard: { label: "Hard", enemyHealth: 1.25, enemyDamage: 1.25, enemySpeed: 1.08, attackSpeed: 1.12, spawnCount: 1.22, flagHealth: 0.88, xpMultiplier: 1.2 },
    extreme: { label: "Extreme", enemyHealth: 1.65, enemyDamage: 1.6, enemySpeed: 1.18, attackSpeed: 1.3, spawnCount: 1.55, flagHealth: 0.72, xpMultiplier: 1.55 },
  } satisfies Record<Difficulty, { label: string; enemyHealth: number; enemyDamage: number; enemySpeed: number; attackSpeed: number; spawnCount: number; flagHealth: number; xpMultiplier: number }>,
  bossDifficulty: {
    easy: { health: 0.84, damage: 0.8, speed: 0.96, attackSpeed: 0.94 },
    normal: { health: 1, damage: 1, speed: 1, attackSpeed: 1 },
    hard: { health: 1.18, damage: 1.16, speed: 1.05, attackSpeed: 1.08 },
    extreme: { health: 1.38, damage: 1.32, speed: 1.1, attackSpeed: 1.16 },
  } satisfies Record<Difficulty, { health: number; damage: number; speed: number; attackSpeed: number }>,
  upgrades: {
    moveSpeed: { name: "Fleet Feet", amount: 0.08 },
    maxHealth: { name: "Heartwood", amount: 20 },
    punchRate: { name: "Fast Hands", amount: 0.1 },
    punchDamage: { name: "Heavy Hands", amount: 5 },
    bowRate: { name: "Quick Draw", amount: 0.08 },
    bowDamage: { name: "Sharp Arrows", amount: 4 },
    harvestRate: { name: "Gatherer's Rhythm", amount: 0.1 },
    repairEfficiency: { name: "Careful Repairs", amount: 0.2 },
    structureDurability: { name: "Fortified", amount: 0.12 },
    costReduction: { name: "Efficient Builder", amount: 0.08 },
    turretDamage: { name: "Turret Power", amount: 0.15 },
    turretRate: { name: "Turret Gears", amount: 0.1 },
    turretRange: { name: "Long Sight", amount: 0.1 },
    harvesterSpeed: { name: "Harvester Gears", amount: 0.18 },
    flagHealth: { name: "Sturdy Standard", amount: 20 },
    turretCapacity: { name: "Expanded Arsenal", amount: 1 },
    harvesterCapacity: { name: "Expanded Workshop", amount: 1 },
  },
  upgradeCaps: {
    moveSpeed: 0.4,
    maxHealth: 100,
    punchRate: 0.6,
    punchDamage: 30,
    bowRate: 0.48,
    bowDamage: 24,
    harvestRate: 0.6,
    repairEfficiency: 1,
    structureDurability: 0.72,
    costReduction: 0.4,
    turretDamage: 0.9,
    turretRate: 0.6,
    turretRange: 0.6,
    harvesterSpeed: 0.9,
    flagHealth: 100,
    turretCapacity: 5,
    harvesterCapacity: 5,
  } satisfies Record<keyof Upgrades, number>,
  mutations: {
    basicWeight: { name: "Shambling Crowd", amount: 12 },
    runnerWeight: { name: "Running Pack", amount: 10 },
    breakerWeight: { name: "Siege Line", amount: 8 },
    jumperWeight: { name: "Leaping Horde", amount: 8 },
    summonerWeight: { name: "Dark Chorus", amount: 6 },
    health: { name: "Thick Skulls", amount: 0.12 },
    damage: { name: "Vicious Claws", amount: 0.1 },
    speed: { name: "Restless Dead", amount: 0.06 },
    attackSpeed: { name: "Frenzy", amount: 0.08 },
    structureDamage: { name: "Sunderers", amount: 0.12 },
    waveSize: { name: "Rising Dead", amount: 3 },
  },
} as const;

export const TIER_ORDER: Tier[] = ["wood", "stone", "gold", "diamond"];
export const RESOURCE_ORDER: ResourceKind[] = ["wood", "stone", "gold", "diamond"];
export const STRUCTURE_ORDER: StructureKind[] = ["wall", "spikes", "door", "harvester", "turret"];
